"use client";
import type {LessonScene} from "../../lib/course-types";
import {SceneChoice} from "./SceneChoice";
const opts=(...labels:string[])=>labels.map(label=>({label}));
const ruler=(labels:string[])=><div className="measure-ruler">{labels.map((v,i)=><span key={`${v}-${i}`}>{v}</span>)}</div>;
const shape=(labels:string[])=><div className="perimeter-shape">{labels.map((v,i)=><span key={`${v}-${i}`}>{v}</span>)}</div>;
const areaGrid=(full:number,partial=0)=><div className="area-square-grid">{Array.from({length:Math.max(full+partial,6)},(_,i)=><i className={i<full?"full":i<full+partial?"partial":""} key={i}/>)}</div>;
const transform=(kind:"triangle"|"parallelogram",label:string)=><div className={`shape-transform ${kind}`}><i/><i/><b>{label}</b></div>;
const configs:Record<string,{visual:React.ReactNode;options:{label:string}[];answer:string}>={
"length-meaning":{visual:ruler(["A","距离","B"]),options:opts("两点之间的距离","物体的重量","经过的时间"),answer:"两点之间的距离"},"length-unit-scale":{visual:ruler(["km","m","cm","mm"]),options:opts("千米","厘米","毫米"),answer:"千米"},"length-cm-mm":{visual:ruler(["60cm","×10","600mm"]),options:opts("60mm","600mm","6000mm"),answer:"600mm"},"length-cm-m":{visual:ruler(["60cm","÷100","0.6m"]),options:opts("0.6m","6m","60m"),answer:"0.6m"},"length-choose-unit":{visual:ruler(["黄蜂","15 ?"]),options:opts("千米","米","毫米"),answer:"毫米"},
"length-tree-growth":{visual:ruler(["15.4m","→","16.6m"]),options:opts("0.2m","1.2m","2.2m"),answer:"1.2m"},"length-year-average":{visual:ruler(["1.2m","÷4","0.3m"]),options:opts("0.3m","3m","4.8m"),answer:"0.3m"},"length-convert-km":{visual:ruler(["1.2km","×1000","1200m"]),options:opts("120m","1200m","12000m"),answer:"1200m"},"length-route-total":{visual:ruler(["760m","1200m","630m"]),options:opts("1590m","2590m","3590m"),answer:"2590m"},"length-route-km":{visual:ruler(["2590m","÷1000","2.59km"]),options:opts("0.259km","2.59km","25.9km"),answer:"2.59km"},
"perimeter-meaning":{visual:shape(["边","边","边","边"]),options:opts("所有边的总长度","图形内部大小","最长的一条边"),answer:"所有边的总长度"},"perimeter-court":{visual:shape(["11","24","11","24"]),options:opts("35m","70m","264m"),answer:"70m"},"perimeter-opposite":{visual:shape(["12","9","?"]),options:opts("9+?=12","9×?=12","12+?=9"),answer:"9+?=12"},"perimeter-missing":{visual:shape(["12−9","?"]),options:opts("2m","3m","4m"),answer:"3m"},"perimeter-complex":{visual:shape(["12","6","9","5","3","11"]),options:opts("36m","46m","56m"),answer:"46m"},
"formula-rectangle":{visual:shape(["a","b","a","b"]),options:opts("a+b","2(a+b)","ab"),answer:"2(a+b)"},"formula-square":{visual:shape(["2","2","2","2"]),options:opts("4cm","8cm","16cm"),answer:"8cm"},"formula-parallelogram":{visual:shape(["3","5","3","5"]),options:opts("8cm","16cm","30cm"),answer:"16cm"},"formula-equilateral":{visual:transform("triangle","a+a+a"),options:opts("2a","3a","a²"),answer:"3a"},"formula-isosceles":{visual:transform("triangle","7 + 7 + 5 = 19"),options:opts("6cm","7cm","8cm"),answer:"7cm"},
"area-meaning":{visual:areaGrid(6),options:opts("图形内部空间","图形边界总长","最高点"),answer:"图形内部空间"},"area-unit-square":{visual:areaGrid(1),options:opts("1m","1m²","1m³"),answer:"1m²"},"area-garden-grid":{visual:areaGrid(6),options:opts("5块","6块","8块"),answer:"6块"},"area-count":{visual:areaGrid(6),options:opts("5m²","6m²","10m²"),answer:"6m²"},"area-vs-perimeter":{visual:areaGrid(6),options:opts("内部着色部分","外圈边线","最长一边"),answer:"内部着色部分"},
"estimate-area-grid":{visual:areaGrid(8,8),options:opts("帮助量化覆盖面积","只测周长","寻找最高点"),answer:"帮助量化覆盖面积"},"estimate-area-full":{visual:areaGrid(18),options:opts("18m²","26m²","36m²"),answer:"18m²"},"estimate-area-partial":{visual:areaGrid(0,26),options:opts("约13m²","约26m²","约52m²"),answer:"约13m²"},"estimate-area-combine":{visual:areaGrid(18,13),options:opts("21m²","31m²","41m²"),answer:"31m²"},"estimate-area-language":{visual:areaGrid(18,13),options:opts("约31m²","精确31m²","周长31m"),answer:"约31m²"},
"triangle-copy":{visual:transform("triangle","两个三角形 → 长方形"),options:opts("长方形","圆形","五边形"),answer:"长方形"},"triangle-half":{visual:transform("triangle","½"),options:opts("三角形是长方形一半","三角形是两倍","面积相差1"),answer:"三角形是长方形一半"},"triangle-height":{visual:transform("triangle","高 ⟂ 底"),options:opts("顶点到底边的垂线","任意斜边","最长一边"),answer:"顶点到底边的垂线"},"triangle-formula":{visual:transform("triangle","底×高÷2"),options:opts("底×高","底×高÷2","底+高"),answer:"底×高÷2"},"triangle-example":{visual:transform("triangle","8×5÷2"),options:opts("13cm²","20cm²","40cm²"),answer:"20cm²"},
"parallelogram-cut":{visual:transform("parallelogram","作垂线切角"),options:opts("垂直于底边","平行于底边","沿斜边"),answer:"垂直于底边"},"parallelogram-slide":{visual:transform("parallelogram","切下 → 平移"),options:opts("长方形","三角形","圆形"),answer:"长方形"},"parallelogram-base":{visual:transform("parallelogram","底 = 长"),options:opts("原底对应长方形的长","斜边对应长","周长对应长"),answer:"原底对应长方形的长"},"parallelogram-height":{visual:transform("parallelogram","高 = 宽"),options:opts("垂直高度","斜边长度","任意边长"),answer:"垂直高度"},"parallelogram-formula":{visual:transform("parallelogram","8×5"),options:opts("13cm²","20cm²","40cm²"),answer:"40cm²"},
};
export function MeasurementScene({scene,onComplete}:{scene:LessonScene;onComplete:(correct:number,attempts:number)=>void}){return <SceneChoice {...(configs[scene.id]??configs["length-meaning"])} onComplete={onComplete} className="measurement-scene"/>;}
