import type { Course } from "./course-types";

export const courses: Course[] = [
  {
    id: "symbols",
    number: "01",
    title: "数字符号",
    summary: "从真实数量出发，发现人类如何用简洁符号记录世界。",
    duration: "约 12 分钟",
    accent: "#e45b3d",
    goals: ["区分数量与数字", "认识多种数字写法", "用符号准确表达数量"],
    scenes: [
      { id: "count-first", kind: "count", eyebrow: "观察实验", title: "数量一直都在那里", body: "在数字出现以前，人们也能感受到多少。点击果实，看看数量怎样变化。", instruction: "点击果实，收集正好 5 个。" },
      { id: "symbol-story", kind: "story", eyebrow: "时间旅行", title: "把“多少”留下来", body: "一条刻痕代表一个物体。刻痕越来越多，人们开始发明更快速、更统一的符号。", instruction: "逐步点亮刻痕，观察它如何变成数字 5。" },
      { id: "many-symbols", kind: "match", eyebrow: "配对实验", title: "一种数量，多种写法", body: "阿拉伯数字、汉字和罗马数字长得不同，却可以表达同一个数量。", instruction: "选择所有表示三个的卡片。" },
      { id: "symbol-sort", kind: "match", eyebrow: "拖放挑战", title: "让符号找到数量", body: "符号不是装饰，它必须与真实数量准确对应。", instruction: "把数字卡与圆点卡配成正确的一组。" },
      { id: "symbol-quiz", kind: "quiz", eyebrow: "终局测验", title: "数字观察员认证", body: "用三道题检验你是否掌握了数量与符号。", questions: [
        { prompt: "哪一项表达了四个物体？", options: ["● ● ●", "● ● ● ●", "● ● ● ● ●"], answer: 1, explanation: "数一数，四个圆点与数字 4 对应。" },
        { prompt: "哪些符号与数字 3 表示相同数量？", options: ["三", "Ⅱ", "五"], answer: 0, explanation: "汉字“三”和阿拉伯数字 3 表示相同数量。" },
        { prompt: "为什么人们需要数字符号？", options: ["让颜色更漂亮", "快速记录和交流数量", "替代所有文字"], answer: 1, explanation: "统一的数字符号让数量容易记录、计算和交流。" },
      ] },
    ],
  },
  {
    id: "place-value",
    number: "02",
    title: "位值",
    summary: "把数字放进数位屋，理解同一个数字为什么会拥有不同价值。",
    duration: "约 14 分钟",
    accent: "#d39b24",
    goals: ["认识个十百位", "展开三位数", "理解位置决定数值"],
    scenes: [
      { id: "bundle-ten", kind: "build", eyebrow: "积木实验", title: "十个一，组成一个十", body: "零散的单位积木达到十个，就能捆成一条十。", instruction: "连续加入单位块，凑成一条十。" },
      { id: "place-house", kind: "place", eyebrow: "数位屋", title: "每个位置都有名字", body: "从右向左依次是个位、十位、百位。位置不同，数字的价值也不同。", instruction: "把 3、5、2 放进正确位置，组成 352。" },
      { id: "expanded", kind: "place", eyebrow: "拆解实验", title: "把 352 打开看看", body: "百位上的 3 是 300，十位上的 5 是 50，个位上的 2 是 2。", instruction: "点击每个数位，完成 352 = 300 + 50 + 2。" },
      { id: "same-five", kind: "place", eyebrow: "对比观察", title: "同一个 5，价值大不同", body: "305 里的 5 在个位，表示 5；350 里的 5 在十位，表示 50。", instruction: "选择数字 5 价值更大的数。" },
      { id: "build-number", kind: "build", eyebrow: "造数挑战", title: "用积木造出 241", body: "两个百、四个十和一个一组合起来，就是 241。", instruction: "依次完成百位、十位和个位。" },
      { id: "place-quiz", kind: "quiz", eyebrow: "终局测验", title: "数位建筑师认证", body: "用三道题检查你的位值理解。", questions: [
        { prompt: "472 中的 7 表示多少？", options: ["7", "70", "700"], answer: 1, explanation: "7 在十位，所以表示 7 个十，也就是 70。" },
        { prompt: "300 + 20 + 6 组成哪个数？", options: ["326", "362", "236"], answer: 0, explanation: "3 个百、2 个十、6 个一组成 326。" },
        { prompt: "哪个数中的 5 表示 500？", options: ["152", "251", "521"], answer: 2, explanation: "521 中的 5 在百位，表示 500。" },
      ] },
    ],
  },
  {
    id: "sequences",
    number: "03",
    title: "数列与规律",
    summary: "追踪数字每一步的变化，像侦探一样找出隐藏规则。",
    duration: "约 13 分钟",
    accent: "#4f7f6f",
    goals: ["识别递增递减", "描述变化规则", "预测后续数字"],
    scenes: [
      { id: "jump-two", kind: "sequence", eyebrow: "跳格观察", title: "每次向前跳两格", body: "从 2 出发，每次加 2，就会依次来到 4、6、8。相邻两个数的差保持不变。", instruction: "选择数列 2、4、6、8 后面的数字。" },
      { id: "find-five", kind: "sequence", eyebrow: "发现规则", title: "相邻数字变了多少？", body: "观察 5、10、15、20。每前进一步，数字都增加相同的数量。", instruction: "选择这个数列每次增加多少。" },
      { id: "fill-sequence", kind: "sequence", eyebrow: "补全数列", title: "把空缺的数字找回来", body: "规律像一条看不见的轨道。只要知道每次的变化，就能找回空缺。", instruction: "补全 3、6、9、□、15。" },
      { id: "count-down", kind: "sequence", eyebrow: "倒着走", title: "数字也可以越来越小", body: "递减数列每次减去相同的数。30、25、20 正在每次减少 5。", instruction: "选择 30、25、20 后面的数字。" },
      { id: "rule-detective", kind: "sequence", eyebrow: "规则侦探", title: "同样变大，规则可能不同", body: "2、4、8、16 不是每次加同一个数，而是每次变成原来的两倍。", instruction: "找出 2、4、8、16 的规则。" },
      { id: "sequence-quiz", kind: "quiz", eyebrow: "终局测验", title: "数列侦探认证", body: "用三道题证明你能发现并延续数字规律。", questions: [
        { prompt: "4、7、10、13 后面是什么？", options: ["14", "15", "16"], answer: 2, explanation: "每次加 3，所以 13 + 3 = 16。" },
        { prompt: "40、35、30 的规则是什么？", options: ["每次减 5", "每次加 5", "每次减 10"], answer: 0, explanation: "相邻两个数都相差 5，并且越来越小。" },
        { prompt: "3、6、12、24 后面是什么？", options: ["27", "36", "48"], answer: 2, explanation: "每个数都是前一个数的 2 倍，所以 24 × 2 = 48。" },
      ] },
    ],
  },
  {
    id: "shape-patterns",
    number: "04",
    title: "数列与图形",
    summary: "让颜色、形状和方向开口说话，把看见的变化变成规律。",
    duration: "约 14 分钟",
    accent: "#5d6faa",
    goals: ["识别循环单元", "延续图形规律", "图形转化为数列"],
    scenes: [
      { id: "color-cycle", kind: "visual-pattern", eyebrow: "颜色循环", title: "找到不断重复的小队", body: "红、黄、绿三个颜色组成一个重复单元。看清最小单元，就能一直延续下去。", instruction: "选择下一个应该出现的颜色。" },
      { id: "shape-chain", kind: "visual-pattern", eyebrow: "形状接龙", title: "圆、三角、方形轮流登场", body: "图形也可以按照固定顺序循环。找到开头，观察它何时重新出现。", instruction: "补全圆、三角、方形、圆、三角、□。" },
      { id: "turn-arrow", kind: "visual-pattern", eyebrow: "方向规律", title: "箭头每次转四分之一圈", body: "向上、向右、向下、向左，箭头每次顺时针旋转 90°。", instruction: "选择向左之后的箭头方向。" },
      { id: "growing-dots", kind: "visual-pattern", eyebrow: "增长图案", title: "每幅图多两个圆点", body: "第一幅 1 个点，第二幅 3 个点，第三幅 5 个点。图形在增长，数量也形成数列。", instruction: "选择第四幅图应该有多少个点。" },
      { id: "picture-to-number", kind: "visual-pattern", eyebrow: "图形变数字", title: "把看见的规律写下来", body: "点阵 1、3、5、7 对应每次增加 2 的奇数数列。图形规律可以翻译成数字规律。", instruction: "选择下一个点阵的数量。" },
      { id: "pattern-quiz", kind: "quiz", eyebrow: "终局测验", title: "图形规律设计师认证", body: "用三道题检验你是否能看懂图形语言。", questions: [
        { prompt: "○ △ □ ○ △ 后面是什么？", options: ["○", "△", "□"], answer: 2, explanation: "重复单元是圆、三角、方形，下一项是方形。" },
        { prompt: "箭头按 ↑ → ↓ ← 循环，← 后面是什么？", options: ["↑", "→", "↓"], answer: 0, explanation: "向左之后回到向上，开始下一轮循环。" },
        { prompt: "点数是 2、4、6、8，下一幅图有几个点？", options: ["9", "10", "12"], answer: 1, explanation: "每幅图增加 2 个点，所以 8 + 2 = 10。" },
      ] },
    ],
  },
  {
    id: "signed-numbers",
    number: "05",
    title: "正数与负数",
    summary: "站在零的两边，用温度、楼层和方向理解正数与负数。",
    duration: "约 15 分钟",
    accent: "#3c86a4",
    goals: ["理解零是分界", "认识正负方向", "比较正负数大小"],
    scenes: [
      { id: "temperature", kind: "number-line", eyebrow: "温度实验", title: "零上与零下", body: "0°C 是冰水交界附近的温度。零上用正数表示，零下用负数表示。", instruction: "选择表示零下 3°C 的数字。" },
      { id: "number-walk", kind: "number-line", eyebrow: "数轴漫步", title: "从零出发，方向决定正负", body: "在数轴上，0 的右边是正数，左边是负数。离 0 越远，绝对距离越大。", instruction: "从 0 向左走 4 格，会到达哪里？" },
      { id: "elevator", kind: "number-line", eyebrow: "电梯楼层", title: "地面之上与地下", body: "地面层记作 0，地上楼层可用正数，地下停车层可用负数。", instruction: "选择地下 2 层对应的数。" },
      { id: "compare-signed", kind: "number-line", eyebrow: "谁更大", title: "越靠右，数字越大", body: "在数轴上比较数字时，右边的数总比左边的大，所以 0 大于所有负数。", instruction: "在 -2、0、3 中选择最大的数。" },
      { id: "signed-context", kind: "number-line", eyebrow: "情境配对", title: "生活中的相反方向", body: "收入与支出、上升与下降都可以用正负数表示。符号告诉我们变化的方向。", instruction: "账户支出 5 元应该用哪个数表示？" },
      { id: "signed-quiz", kind: "quiz", eyebrow: "终局测验", title: "正负数导航员认证", body: "用三道题检查你能否在零的两边准确定位。", questions: [
        { prompt: "数轴上哪个数最靠右？", options: ["-4", "-1", "2"], answer: 2, explanation: "正数在 0 的右边，2 比两个负数都大。" },
        { prompt: "温度从 2°C 降到 -3°C，一共下降多少度？", options: ["1°C", "5°C", "6°C"], answer: 1, explanation: "从 2 到 0 是 2 度，从 0 到 -3 是 3 度，共 5 度。" },
        { prompt: "地下 3 层通常写作什么？", options: ["+3", "0", "-3"], answer: 2, explanation: "地下方向相对于地面为负，所以写作 -3。" },
      ] },
    ],
  },
];
